'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8669.
'
Namespace SATWebSV
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SATWebSVSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SATWebSV
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://thsatitsv002/satwebsv1/satwebsv.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginHelloWorld(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("HelloWorld", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndHelloWorld(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/connectDB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function connectDB(ByVal strConn As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("connectDB", New Object() {strConn})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginconnectDB(ByVal strConn As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("connectDB", New Object() {strConn}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndconnectDB(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectData(ByVal strJob As String, ByVal suffix As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectData", New Object() {strJob, suffix})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectData(ByVal strJob As String, ByVal suffix As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectData", New Object() {strJob, suffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectData(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectDataBillet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectDataBillet(ByVal item As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectDataBillet", New Object() {item})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectDataBillet(ByVal item As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectDataBillet", New Object() {item}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectDataBillet(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectDataJobItem", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectDataJobItem(ByVal strJob As String, ByVal strSuffix As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectDataJobItem", New Object() {strJob, strSuffix})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectDataJobItem(ByVal strJob As String, ByVal strSuffix As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectDataJobItem", New Object() {strJob, strSuffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectDataJobItem(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectData_Test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectData_Test(ByVal strJob As String, ByVal suffix As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectData_Test", New Object() {strJob, suffix})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectData_Test(ByVal strJob As String, ByVal suffix As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectData_Test", New Object() {strJob, suffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectData_Test(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectDataTO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectDataTO(ByVal strTrnNum As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectDataTO", New Object() {strTrnNum})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectDataTO(ByVal strTrnNum As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectDataTO", New Object() {strTrnNum}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectDataTO(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLable", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLable(ByVal strLable As String)
            Me.Invoke("PrintLable", New Object() {strLable})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLable(ByVal strLable As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLable", New Object() {strLable}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLable(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelBillet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLabelBillet(ByVal strPO As String, ByVal strPOLine As String, ByVal qty As Integer)
            Me.Invoke("PrintLabelBillet", New Object() {strPO, strPOLine, qty})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLabelBillet(ByVal strPO As String, ByVal strPOLine As String, ByVal qty As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLabelBillet", New Object() {strPO, strPOLine, qty}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLabelBillet(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelBilletDirect", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLabelBilletDirect(ByVal strItem As String, ByVal strLot As String, ByVal qty As Integer)
            Me.Invoke("PrintLabelBilletDirect", New Object() {strItem, strLot, qty})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLabelBilletDirect(ByVal strItem As String, ByVal strLot As String, ByVal qty As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLabelBilletDirect", New Object() {strItem, strLot, qty}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLabelBilletDirect(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelAEPacking", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLabelAEPacking(ByVal strJob As String, ByVal strSuffix As String)
            Me.Invoke("PrintLabelAEPacking", New Object() {strJob, strSuffix})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLabelAEPacking(ByVal strJob As String, ByVal strSuffix As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLabelAEPacking", New Object() {strJob, strSuffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLabelAEPacking(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelAEPacking_test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLabelAEPacking_test(ByVal strJob As String, ByVal strSuffix As String)
            Me.Invoke("PrintLabelAEPacking_test", New Object() {strJob, strSuffix})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLabelAEPacking_test(ByVal strJob As String, ByVal strSuffix As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLabelAEPacking_test", New Object() {strJob, strSuffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLabelAEPacking_test(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveLocation", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MoveLocation(ByVal strJob As String, ByVal strSuffix As Integer, ByVal loc As String) As String
            Dim results() As Object = Me.Invoke("MoveLocation", New Object() {strJob, strSuffix, loc})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginMoveLocation(ByVal strJob As String, ByVal strSuffix As Integer, ByVal loc As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MoveLocation", New Object() {strJob, strSuffix, loc}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndMoveLocation(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveSILocation", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MoveSILocation(ByVal strJob As String, ByVal strSuffix As Integer, ByVal strSloc As String, ByVal strEloc As String, ByVal qty_move As String) As String
            Dim results() As Object = Me.Invoke("MoveSILocation", New Object() {strJob, strSuffix, strSloc, strEloc, qty_move})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginMoveSILocation(ByVal strJob As String, ByVal strSuffix As Integer, ByVal strSloc As String, ByVal strEloc As String, ByVal qty_move As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MoveSILocation", New Object() {strJob, strSuffix, strSloc, strEloc, qty_move}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndMoveSILocation(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MovePackingLocation", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MovePackingLocation(ByVal strItem As String, ByVal strLot As String, ByVal strSWhse As String, ByVal strEWhse As String, ByVal strSloc As String, ByVal strEloc As String, ByVal qty_move As String) As String
            Dim results() As Object = Me.Invoke("MovePackingLocation", New Object() {strItem, strLot, strSWhse, strEWhse, strSloc, strEloc, qty_move})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginMovePackingLocation(ByVal strItem As String, ByVal strLot As String, ByVal strSWhse As String, ByVal strEWhse As String, ByVal strSloc As String, ByVal strEloc As String, ByVal qty_move As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MovePackingLocation", New Object() {strItem, strLot, strSWhse, strEWhse, strSloc, strEloc, qty_move}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndMovePackingLocation(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectReason", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectReason() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectReason", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectReason(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectReason", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectReason(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectMiscIssueReason", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectMiscIssueReason() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectMiscIssueReason", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectMiscIssueReason(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectMiscIssueReason", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectMiscIssueReason(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectFaultCode", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectFaultCode() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectFaultCode", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectFaultCode(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectFaultCode", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectFaultCode(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectLot", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectLot(ByVal strItem As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("selectLot", New Object() {strItem})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BeginselectLot(ByVal strItem As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectLot", New Object() {strItem}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectLot(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectQty", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectQty(ByVal strJob As String, ByVal suffix As Integer) As Integer
            Dim results() As Object = Me.Invoke("selectQty", New Object() {strJob, suffix})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginselectQty(ByVal strJob As String, ByVal suffix As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectQty", New Object() {strJob, suffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectQty(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectQty_rev1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectQty_rev1(ByVal strJob As String, ByVal suffix As Integer, ByVal oper As String) As Integer
            Dim results() As Object = Me.Invoke("selectQty_rev1", New Object() {strJob, suffix, oper})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginselectQty_rev1(ByVal strJob As String, ByVal suffix As Integer, ByVal oper As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectQty_rev1", New Object() {strJob, suffix, oper}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectQty_rev1(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/selectQty_rev2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function selectQty_rev2(ByVal strJob As String, ByVal suffix As Integer, ByVal oper As String) As Integer
            Dim results() As Object = Me.Invoke("selectQty_rev2", New Object() {strJob, suffix, oper})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginselectQty_rev2(ByVal strJob As String, ByVal suffix As Integer, ByVal oper As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("selectQty_rev2", New Object() {strJob, suffix, oper}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndselectQty_rev2(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQtyBeforeMove", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getQtyBeforeMove(ByVal strJob As String, ByVal suffix As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getQtyBeforeMove", New Object() {strJob, suffix})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BegingetQtyBeforeMove(ByVal strJob As String, ByVal suffix As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getQtyBeforeMove", New Object() {strJob, suffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetQtyBeforeMove(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQtyBeforeMoveWH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getQtyBeforeMoveWH(ByVal strItem As String, ByVal strLot As String, ByVal strLoc As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getQtyBeforeMoveWH", New Object() {strItem, strLot, strLoc})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BegingetQtyBeforeMoveWH(ByVal strItem As String, ByVal strLot As String, ByVal strLoc As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getQtyBeforeMoveWH", New Object() {strItem, strLot, strLoc}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetQtyBeforeMoveWH(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getJobFromItemLot", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getJobFromItemLot(ByVal strItem As String, ByVal strLot As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getJobFromItemLot", New Object() {strItem, strLot})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BegingetJobFromItemLot(ByVal strItem As String, ByVal strLot As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getJobFromItemLot", New Object() {strItem, strLot}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetJobFromItemLot(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TranferExits", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TranferExits(ByVal strTrnNum As String) As Integer
            Dim results() As Object = Me.Invoke("TranferExits", New Object() {strTrnNum})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BeginTranferExits(ByVal strTrnNum As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TranferExits", New Object() {strTrnNum}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndTranferExits(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TranferCheckCust", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TranferCheckCust(ByVal strTrnNum As String) As String
            Dim results() As Object = Me.Invoke("TranferCheckCust", New Object() {strTrnNum})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginTranferCheckCust(ByVal strTrnNum As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TranferCheckCust", New Object() {strTrnNum}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndTranferCheckCust(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertJobTrans", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertJobTrans(ByVal strJob As String, ByVal strSuffix As Integer, ByVal oper As Integer, ByVal qtyRel As Integer, ByVal qtyScrap As Integer, ByVal strReason As String) As String
            Dim results() As Object = Me.Invoke("insertJobTrans", New Object() {strJob, strSuffix, oper, qtyRel, qtyScrap, strReason})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertJobTrans(ByVal strJob As String, ByVal strSuffix As Integer, ByVal oper As Integer, ByVal qtyRel As Integer, ByVal qtyScrap As Integer, ByVal strReason As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertJobTrans", New Object() {strJob, strSuffix, oper, qtyRel, qtyScrap, strReason}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertJobTrans(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertJobTrans_rev1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertJobTrans_rev1(ByVal strJob As String, ByVal strSuffix As Integer, ByVal oper As Integer, ByVal qtyRel As Integer, ByVal qtyScrap As Integer, ByVal strReason As String, ByVal strCause As String, ByVal strFeature As String) As String
            Dim results() As Object = Me.Invoke("insertJobTrans_rev1", New Object() {strJob, strSuffix, oper, qtyRel, qtyScrap, strReason, strCause, strFeature})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertJobTrans_rev1(ByVal strJob As String, ByVal strSuffix As Integer, ByVal oper As Integer, ByVal qtyRel As Integer, ByVal qtyScrap As Integer, ByVal strReason As String, ByVal strCause As String, ByVal strFeature As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertJobTrans_rev1", New Object() {strJob, strSuffix, oper, qtyRel, qtyScrap, strReason, strCause, strFeature}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertJobTrans_rev1(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertManifest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertManifest(ByVal Seq As Integer, ByVal strPOCust As String, ByVal strItemCust As String, ByVal strSNYN As String, ByVal strItem As String, ByVal strQty As Integer, ByVal strLoc As String, ByVal strPlant As String, ByVal strCofC As String) As String
            Dim results() As Object = Me.Invoke("insertManifest", New Object() {Seq, strPOCust, strItemCust, strSNYN, strItem, strQty, strLoc, strPlant, strCofC})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertManifest(ByVal Seq As Integer, ByVal strPOCust As String, ByVal strItemCust As String, ByVal strSNYN As String, ByVal strItem As String, ByVal strQty As Integer, ByVal strLoc As String, ByVal strPlant As String, ByVal strCofC As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertManifest", New Object() {Seq, strPOCust, strItemCust, strSNYN, strItem, strQty, strLoc, strPlant, strCofC}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertManifest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertTrnItem", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertTrnItem(ByVal strTrnNum As String, ByVal strBox As String, ByVal strJob As String, ByVal strSuffix As Integer, ByVal qty As Integer, ByVal fprint As Boolean) As String
            Dim results() As Object = Me.Invoke("insertTrnItem", New Object() {strTrnNum, strBox, strJob, strSuffix, qty, fprint})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertTrnItem(ByVal strTrnNum As String, ByVal strBox As String, ByVal strJob As String, ByVal strSuffix As Integer, ByVal qty As Integer, ByVal fprint As Boolean, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertTrnItem", New Object() {strTrnNum, strBox, strJob, strSuffix, qty, fprint}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertTrnItem(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLableSingle", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLableSingle(ByVal strJob As String, ByVal strSuffix As String)
            Me.Invoke("PrintLableSingle", New Object() {strJob, strSuffix})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLableSingle(ByVal strJob As String, ByVal strSuffix As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLableSingle", New Object() {strJob, strSuffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLableSingle(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertSerial", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertSerial(ByVal strTO As String, ByVal strBox As String, ByVal strCofC As String, ByVal strItem As String, ByVal strLot As String, ByVal qty As Integer, ByVal strSerial As String) As String
            Dim results() As Object = Me.Invoke("insertSerial", New Object() {strTO, strBox, strCofC, strItem, strLot, qty, strSerial})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertSerial(ByVal strTO As String, ByVal strBox As String, ByVal strCofC As String, ByVal strItem As String, ByVal strLot As String, ByVal qty As Integer, ByVal strSerial As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertSerial", New Object() {strTO, strBox, strCofC, strItem, strLot, qty, strSerial}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertSerial(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrnItemQtyRemain", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TrnItemQtyRemain(ByVal strTO As String, ByVal strItem As String, ByVal strCoC As String) As String
            Dim results() As Object = Me.Invoke("TrnItemQtyRemain", New Object() {strTO, strItem, strCoC})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginTrnItemQtyRemain(ByVal strTO As String, ByVal strItem As String, ByVal strCoC As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TrnItemQtyRemain", New Object() {strTO, strItem, strCoC}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndTrnItemQtyRemain(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQtyMove1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getQtyMove1(ByVal strItem As String, ByVal strLot As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getQtyMove1", New Object() {strItem, strLot})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BegingetQtyMove1(ByVal strItem As String, ByVal strLot As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getQtyMove1", New Object() {strItem, strLot}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetQtyMove1(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getChemLastestLot", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getChemLastestLot(ByVal strItem As String, ByVal strLot As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("getChemLastestLot", New Object() {strItem, strLot})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Function BegingetChemLastestLot(ByVal strItem As String, ByVal strLot As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getChemLastestLot", New Object() {strItem, strLot}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetChemLastestLot(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveBillet", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MoveBillet(ByVal strItem As String, ByVal strLot As String, ByVal strSLoc As String, ByVal strELoc As String, ByVal qty As Integer) As String
            Dim results() As Object = Me.Invoke("MoveBillet", New Object() {strItem, strLot, strSLoc, strELoc, qty})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginMoveBillet(ByVal strItem As String, ByVal strLot As String, ByVal strSLoc As String, ByVal strELoc As String, ByVal qty As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("MoveBillet", New Object() {strItem, strLot, strSLoc, strELoc, qty}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndMoveBillet(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintCofCToReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PrintCofCToReport(ByVal sCustInvNum As String, ByVal eCustInvNum As String, ByVal sCofCNum As String, ByVal eCofCNum As String, ByVal sCofCDate As String, ByVal eCofCDate As String, ByVal sDoc As String, ByVal user As String) As String
            Dim results() As Object = Me.Invoke("PrintCofCToReport", New Object() {sCustInvNum, eCustInvNum, sCofCNum, eCofCNum, sCofCDate, eCofCDate, sDoc, user})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginPrintCofCToReport(ByVal sCustInvNum As String, ByVal eCustInvNum As String, ByVal sCofCNum As String, ByVal eCofCNum As String, ByVal sCofCDate As String, ByVal eCofCDate As String, ByVal sDoc As String, ByVal user As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintCofCToReport", New Object() {sCustInvNum, eCustInvNum, sCofCNum, eCofCNum, sCofCDate, eCofCDate, sDoc, user}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPrintCofCToReport(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertIHCCheck", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertIHCCheck(ByVal strJob As String, ByVal strSuffix As String, ByVal qty As Integer) As String
            Dim results() As Object = Me.Invoke("insertIHCCheck", New Object() {strJob, strSuffix, qty})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BegininsertIHCCheck(ByVal strJob As String, ByVal strSuffix As String, ByVal qty As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("insertIHCCheck", New Object() {strJob, strSuffix, qty}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndinsertIHCCheck(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQtyIHC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getQtyIHC(ByVal strJob As String, ByVal suffix As Integer) As Integer
            Dim results() As Object = Me.Invoke("getQtyIHC", New Object() {strJob, suffix})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Function BegingetQtyIHC(ByVal strJob As String, ByVal suffix As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("getQtyIHC", New Object() {strJob, suffix}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndgetQtyIHC(ByVal asyncResult As System.IAsyncResult) As Integer
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/closeConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub closeConnection()
            Me.Invoke("closeConnection", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Function BegincloseConnection(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("closeConnection", New Object(-1) {}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndcloseConnection(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintLabelGRN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub PrintLabelGRN(ByVal strGRN As String, ByVal strGRNLine As String)
            Me.Invoke("PrintLabelGRN", New Object() {strGRN, strGRNLine})
        End Sub
        
        '''<remarks/>
        Public Function BeginPrintLabelGRN(ByVal strGRN As String, ByVal strGRNLine As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintLabelGRN", New Object() {strGRN, strGRNLine}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Sub EndPrintLabelGRN(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SAT_MiscIssue", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SAT_MiscIssue(ByVal strItem As String, ByVal Qty_issue As Integer, ByVal strWhse As String, ByVal strLoc As String, ByVal strLot As String, ByVal strReason As String) As String
            Dim results() As Object = Me.Invoke("SAT_MiscIssue", New Object() {strItem, Qty_issue, strWhse, strLoc, strLot, strReason})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginSAT_MiscIssue(ByVal strItem As String, ByVal Qty_issue As Integer, ByVal strWhse As String, ByVal strLoc As String, ByVal strLot As String, ByVal strReason As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SAT_MiscIssue", New Object() {strItem, Qty_issue, strWhse, strLoc, strLot, strReason}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndSAT_MiscIssue(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
