'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8669
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8669.
'
Namespace PrintCofC_R1
    
    '''<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://192.168.1.10/WebServiceCofC/service1.asmx"
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PrintCofCToReport", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function PrintCofCToReport(ByVal sCustInvNum As String, ByVal eCustInvNum As String, ByVal sCofCNum As String, ByVal eCofCNum As String, ByVal sCofCDate As String, ByVal eCofCDate As String, ByVal sDoc As String, ByVal user As String) As String
            Dim results() As Object = Me.Invoke("PrintCofCToReport", New Object() {sCustInvNum, eCustInvNum, sCofCNum, eCofCNum, sCofCDate, eCofCDate, sDoc, user})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginPrintCofCToReport(ByVal sCustInvNum As String, ByVal eCustInvNum As String, ByVal sCofCNum As String, ByVal eCofCNum As String, ByVal sCofCDate As String, ByVal eCofCDate As String, ByVal sDoc As String, ByVal user As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("PrintCofCToReport", New Object() {sCustInvNum, eCustInvNum, sCofCNum, eCofCNum, sCofCDate, eCofCDate, sDoc, user}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndPrintCofCToReport(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
